// Tüm etkinlik ve kurum verileri

export const allEvents = [
  {
    id: 1,
    title: 'Teknoloji ve İnovasyon Zirvesi 2024',
    description: 'Yapay zeka, blockchain ve gelecek teknolojileri hakkında uzman konuşmacıların yer alacağı kapsamlı bir etkinlik. Sektörün önde gelen isimleriyle buluşma fırsatı!',
    organization: {
      id: 1,
      name: 'T.C. Sanayi ve Teknoloji Bakanlığı',
      type: 'Resmi Kurum',
      logo: '',
      verified: true,
    },
    date: '2024-03-15',
    time: '10:00',
    location: 'Ankara, Congresium',
    category: 'Teknoloji',
    attendees: 0,
    interested: 0,
    isUpcoming: true,
  },
  {
    id: 2,
    title: 'Kültür ve Sanat Festivali',
    description: 'Geleneksel Türk sanatları, müzik performansları ve sergilerle dolu bir hafta sonu. Tüm sanatseverler davetlidir!',
    organization: {
      id: 2,
      name: 'T.C. Kültür ve Turizm Bakanlığı',
      type: 'Resmi Kurum',
      logo: '',
      verified: true,
    },
    date: '2024-03-20',
    time: '14:00',
    location: 'İstanbul, Taksim Meydanı',
    category: 'Kültür & Sanat',
    attendees: 0,
    interested: 0,
    isUpcoming: true,
  },
  {
    id: 3,
    title: 'Çevre ve Sürdürülebilirlik Sempozyumu',
    description: 'İklim değişikliği, yenilenebilir enerji ve çevre koruma konularında farkındalık yaratmak için düzenlenen önemli bir etkinlik.',
    organization: {
      id: 3,
      name: 'T.C. Çevre, Şehircilik ve İklim Değişikliği Bakanlığı',
      type: 'Resmi Kurum',
      logo: '',
      verified: true,
    },
    date: '2024-03-25',
    time: '09:30',
    location: 'İzmir, Fuar İzmir',
    category: 'Çevre',
    attendees: 0,
    interested: 0,
    isUpcoming: true,
  },
  {
    id: 4,
    title: 'Gençlik ve Spor Festivali',
    description: 'Gençlerin katılabileceği çeşitli spor aktiviteleri, turnuvalar ve eğlenceli yarışmalar. Sağlıklı yaşam ve spor kültürünü yaygınlaştırmak için!',
    organization: {
      id: 4,
      name: 'T.C. Gençlik ve Spor Bakanlığı',
      type: 'Resmi Kurum',
      logo: '',
      verified: true,
    },
    date: '2024-04-01',
    time: '08:00',
    location: 'Bursa, Merinos Park',
    category: 'Spor',
    attendees: 0,
    interested: 0,
    isUpcoming: true,
  },
  {
    id: 5,
    title: 'Startup Girişimcilik Programı',
    description: 'Yeni girişimcilere yönelik mentorluk ve eğitim programı. Başarılı girişimcilerle buluşma fırsatı!',
    organization: {
      id: 1,
      name: 'T.C. Sanayi ve Teknoloji Bakanlığı',
      type: 'Resmi Kurum',
      logo: '',
      verified: true,
    },
    date: '2024-04-10',
    time: '13:00',
    location: 'İstanbul, Teknopark',
    category: 'Girişimcilik',
    attendees: 0,
    interested: 0,
    isUpcoming: true,
  },
]

export const allOrganizations = [
  {
    id: 1,
    name: 'T.C. Sanayi ve Teknoloji Bakanlığı',
    type: 'Resmi Kurum',
    description: 'Sanayi ve teknoloji alanında politika geliştirme ve uygulama',
    eventsCount: 12,
    verified: true,
    followers: 0,
  },
  {
    id: 2,
    name: 'T.C. Kültür ve Turizm Bakanlığı',
    type: 'Resmi Kurum',
    description: 'Kültür ve turizm alanında faaliyet gösteren resmi kurum',
    eventsCount: 8,
    verified: true,
    followers: 0,
  },
  {
    id: 3,
    name: 'T.C. Çevre, Şehircilik ve İklim Değişikliği Bakanlığı',
    type: 'Resmi Kurum',
    description: 'Çevre koruma ve sürdürülebilirlik konularında çalışmalar yürüten kurum',
    eventsCount: 15,
    verified: true,
    followers: 0,
  },
  {
    id: 4,
    name: 'T.C. Gençlik ve Spor Bakanlığı',
    type: 'Resmi Kurum',
    description: 'Gençlik ve spor alanında faaliyet gösteren resmi kurum',
    eventsCount: 20,
    verified: true,
    followers: 0,
  },
]
